### ISSUE TITLE
Notation like Typescript

### ISSUE THREAD

**Issue by valoricDe** [matthewmueller/graph.ql#26]
I really like your notation of a schema. I thought first it's typescript. Do you think it would make sense to convert your notation completely to typescript notation? Then a typescript developer directly feels home xD

**Comment by valoricDe** [comment]
Have you already seen: https://github.com/calebmer/postgraphql ? If it would be possible to generate the schema directly from a sql database then you even wouldn't need to write the schema yourself. Then if there would be a mapping function from normal graphql definitions to your schema definition then one could enhance the autogenerated schema.

**Comment by matthewmueller** [comment]
I like the idea of typed languages but I wouldn't want to introduce a required compile step on top of this library.

I'm also keeping a close eye on that project and currently experimenting with postgrest :-) since I use Postgres, it makes a lot of sense to stick everything in the DB like that and spend more time modeling the access control inside postgres itself. 

This library and GraphQL are backend glue for your third-party APIs & DBs. You wouldn't want to issue a call to Stripe from a Postgres procedure for example. So this will become supplementary to a main postgres-mapped API.

**Comment by valoricDe** [comment]
Good point with the supplementary api. I already thought about how I am gonna do it.

If someone uses postgraphql or this project and still wants typescript one could use: https://github.com/avantcredit/gql2ts to convert graphql into typescript.
